export const MESSAGE = {
    SUCCESS: {
        USER_CREATED: "User created. Verification email sent.",
        ACCOUNT_VERIFIED: "Your account has been verified successfully!",
        ACCOUNT_LOGGED_IN: 'Logged in successfully',
        SESSION_TOKEN_VALIDATED: 'Session validated successfully',
        EXPENSE_ADDED: 'Expense added successfully',
        EXPENSE_FETCHED: 'Your expenses have been fetched.',
        EXPENSE_UPDATED: 'Expense updated successfully',
        EXPENSE_DELETED: 'Expense deleted successfully',
        CATEGORY_FETCHED: "Category list fetched successfully.",
        CATEGORY_CREATED: "Category created successfully.",
        EXPENSE_GOAL_FETCHED: 'Expense goals fetched successfully',
        SPLIT_EXPENSE_FETCHED: 'Splitwise expenses fetched successfully',
        SPLIT_GROUP_CREATED: 'Group created successfully',
        SPLIT_GROUP_FETCHED: 'Groups fetched successfully',
        SPLIT_GROUP_UPDATED: 'Group updated successfully',
        SPLIT_EXPENSE_CREATED: 'Split Expense created successfully',
        SETTLE_UP_CREATED: 'Settle Up created successfully',
        SETTLE_UP_UPDATED: 'Settle Up updated successfully',
        SETTLE_ACTIVITY_FETCHED: 'Activity fetched successfully',
    },
    ERROR: {
        SOMETHING_WENT_WRONG: 'Something Went Wrong',
        USER_NOT_FOUND: 'Account does not exist. Please register to continue.',
        INVALID_ACCOUNT_PASSWORD: 'Incorrect password. Please try again.',
        INVALID_TOKEN_LINK: 'Verification failed. Invalid or expired verification link.',
        ACCOUNT_NOT_VERIFIED: 'Account not verified. Please check your email...',
        SESSION_TOKEN_MISSING: 'Session token is missing. Please log in again.',
        SESSION_TOKEN_INVALID: 'Invalid or unrecognized session. Please log in again.',
        SESSION_TOKEN_EXPIRED: 'Session expired. Please log in again to continue.',
        EXPENSE_NOT_FOUND: 'No matching expense found. Please try again.',
        INVALID_USER_ID: 'Invalid User ID',
        DUPLICATE_CATEGORY: 'Category name already exists',
        CATEGORY_CREATED: 'Category created successfully',
        CATEGORY_NOT_FOUND: 'Category not found',
        CATEGORY_UPDATED: 'Category updated successfully',
        USER_CATEGORY_CREATED_AT_MISSING: 'User, category, and createdAt are required',
        NO_EXPENSE_GOAL_FOUND: 'No expense goal found for this user, category, and month',
        CREATEDAT_MISSING: 'CreatedAt timestamp is required',
        USERID_CATEGORYID_MISSING: 'userId and categoryId are required.',
        CATEGORY_EXITS_IN_CURRENT_MONTH: 'Category already exists for this month.',
        FAILED_TO_FETCH_UPDATED_EXPENSE: 'Failed to fetch updated expense',
        SETTLE_UP_RECORD_NOT_FOUND: 'Settle Up record not found',
    },
}